### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by aronvaupel** [devhausleipzig/garden-share#22]
Let's put the .tsx and the .stories.tsx  always together in one folder for convenience reasons!!! Agreed?

Add your name below accordingly (edit)

Agree: ...Norman, Aron, T0ny, Jonathan, Simon,
Decline: ...or here

**Comment by nort4n** [comment]
Agree: Norman

**Comment by dnmct** [comment]
I will close the issue since it is resolved
