### ISSUE TITLE
Bug in Emojis

### ISSUE THREAD

**Issue by aronvaupel** [devhausleipzig/garden-share#35]
It is (at least in sb) not possible to close the emoji selector without selecting one.

**Comment by T0ny86** [comment]
easy to solve :)
just select new emoji , and removed it,  if you don't want it any more :P 

any way the version, you have it after last merge , is not the last version
and I don't know how it's happened !
we will rewrite it again as a hot-fix

**Comment by inpatr** [comment]
you can close the picker by clicking on the "+" button again! I think it had this functionality the whole time 🐙
